# Site settings
# Use Tony Fast's credentials to moderate the entire site.
title: Materials Informatics Course Blog
email: tony.fast@gmail.com
description: >
  Course Blog Page for the GT Materials Informatics Course
# Using ``gh`` so the site.github is still available
gh:
  user: Materials-Informatics-Lab
  repo: Materials-Informatics-Lab.github.io
  # Branch hosting Github pages
  branch: master
baseurl: "" # the subpath of your site, e.g. /blog/
url: "Materials-Informatics-Lab.github.io" # the base hostname & protocol for your site
twitter_username: docfast
# Last line in commenting command
disqus: tonyfast

# Build settings
markdown: kramdown

# Pagination of Posts efficiently organizes posts
# Using Pagination in Jekyll here: http://jekyllrb.com/docs/pagination/
paginate: 5
